"""Regenerates src/assets/inter.js from the Inter variable font.

Each cut is instanced from the variable font, subset to Western and Central
European Latin, stored as base64 WOFF2, and paired with its advance widths so
the renderer can measure text without a layout engine.

    curl -LO "https://github.com/google/fonts/raw/main/ofl/inter/Inter%5Bopsz,wght%5D.ttf"
    pip install fonttools brotli
    python scripts/subset-fonts.py "Inter[opsz,wght].ttf"
"""

import base64
import io
import json
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

# Inter has an optical size axis: the text cut for small sizes, display for headlines.
CUTS = {
    "text-400": {"opsz": 14, "wght": 400},
    "text-500": {"opsz": 14, "wght": 500},
    "text-600": {"opsz": 14, "wght": 600},
    "display-700": {"opsz": 32, "wght": 700},
}
# ASCII, Latin-1 Supplement and Latin Extended-A, plus the punctuation the cards use.
CHARACTERS = (
    "".join(chr(code) for code in range(0x20, 0x7F))
    + "".join(chr(code) for code in range(0xA0, 0x180))
    + "‘’“”–—•…′↗€"
)
OUTPUT = Path(__file__).resolve().parent.parent / "src" / "assets" / "inter.js"


def build_cut(source: Path, axes: dict) -> dict:
    font = instantiateVariableFont(TTFont(source), axes)

    options = subset.Options()
    options.layout_features = ["kern"]
    options.hinting = False
    options.name_IDs = [1, 2]
    subsetter = subset.Subsetter(options)
    subsetter.populate(text=CHARACTERS)
    subsetter.subset(font)

    units = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    advance = {
        char: round(font["hmtx"][cmap[ord(char)]][0] / units, 4)
        for char in CHARACTERS
        if ord(char) in cmap
    }

    buffer = io.BytesIO()
    font.flavor = "woff2"
    font.save(buffer)
    return {"woff2": base64.b64encode(buffer.getvalue()).decode(), "advance": advance}


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    source = Path(sys.argv[1])
    cuts = {name: build_cut(source, axes) for name, axes in CUTS.items()}
    header = "// Generated by scripts/subset-fonts.py from Inter (SIL Open Font License 1.1).\n"
    OUTPUT.write_text(f"{header}export default {json.dumps(cuts, ensure_ascii=False)};\n", encoding="utf-8")
    print(f"Wrote {OUTPUT} ({OUTPUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
